# sonar-project.properties
sonar.projectKey=iRatatuii_python-project-52
sonar.organization=iratatuii
sonar.sources=task_manager
sonar.exclusions=**/migrations/**,**/tests.py,**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10

# Игнорировать предупреждения о жестко закодированных паролях в тестах
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/tests.py

