# sonar-project.properties
sonar.projectKey=python-project-52
sonar.sources=.
sonar.exclusions=**/migrations/**,**/tests.py,**/test_*.py

# Игнорировать предупреждения о жестко закодированных паролях в тестах
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/tests.py
